### ISSUE TITLE
[Suggestion] Tents

### ISSUE THREAD

**Issue by Ash70** [TheIllusiveC4/Comforts#1]
Loving your mod btw; thank you for it.
This is just a random idea/suggestion, perhaps it won't fit your view of the mod, so don't feel bad to dismiss it ;)
Tents. I loved the tent that came with "the camping mod" and I thought it could be implemented in your mod as follows:
- Placing the tent sets your spawn.
- Breaking the tent could revert back to your previous (bed) spawn; not sure if that is possible though.
- At night the tent works like a bed.
- It might perhaps give off some light (as if it contains a lamp).

It is for situations where you want to setup camp temporarily. For an idea of the model see the picture below, perhaps with closed flaps though?
![camping1-1024x534](https://user-images.githubusercontent.com/22838247/31567687-03c8abd2-b071-11e7-93d6-fd0f03438d90.png)

**Comment by TheIllusiveC4** [comment]
Thanks for the suggestion, I'm glad you're enjoying my mod. The concept of a tent has been suggested to me by some other people as well, and the question of whether to include it or how to implement it is the main reason I've been delaying a proper release build. I can't make any promises right now, all I can say is that I'm thinking on it and will take your ideas into consideration.

**Comment by TheIllusiveC4** [comment]
I've decided against adding tents, at least for now. I can't think of a way to implement this, both in mechanics and in appearance, that satisfies me or my vision for this mod. My apologies. Perhaps I'll revisit this idea one day or introduce another mod where this could be implemented properly.
