### ISSUE TITLE
[Feature]: Sleeping bag destroy/delete chance option

### ISSUE THREAD

**Issue by Zelerity** [TheIllusiveC4/Comforts#101]
### What is the new feature or improvement?

It would be super cool if you could add a config entry for the chance that a sleeping bag will be destroyed/deleted upon use.
Not to be confused with `sleepingBagBreakage`
I believe many "hardcore" modpacks could benefit from this as well.

**Comment by TheIllusiveC4** [comment]
Maybe I'm not understanding properly, but how is this different than `sleepingBagBreakage`?

**Comment by Zelerity** [comment]
Sorry, I should've been more clear;
`sleepingBagBreakage` doesn't actually delete the item from the game, it breaks the placed sleeping bag block and you can pick it back up.
What I'm looking for here is for the sleeping bag block to break, but the bag item **not** drop.

**Comment by TheIllusiveC4** [comment]
Huh, so just to be clear that's _not_ what `sleepingBagBreakage` is supposed to do. Breaking the sleeping bag and picking it back up is from the `autoUse` feature. What it's _supposed_ to do is exactly what you want. I just tested this myself and this is definitely not behaving like it should, I'm not sure when this feature broke. In any case, I'm now labeling this as a bug.

**Comment by Zelerity** [comment]
That was my first thought as well! I was _convinced_ it was meant to actually remove the sleeping bag. Glad this bug was brought to light. Thank you for all you do! I'm on the latest 1.18.2 RELEASE forge version of the mod, for the record.
