### ISSUE TITLE
[Bug]: Error: net.minecraftforge.fml.ModLoadingException: SpectreLib (spectrelib) encountered an error during the common_setup event phase

### ISSUE THREAD

**Issue by ChilledNyx** [TheIllusiveC4/Comforts#105]
### Minecraft Version

1.19.2

### What happened?

https://imgur.com/a/oREk0rQ
Once I click play, and the game opens, it closes after a second and shows this crash screen, it's meant to open the game and not crash.

### How do you trigger this bug?

1. Open the Launcher from CurseForge
2. Open the All The Mods 8 Modpack
3. Click Play in the Minecraft Launcher
4. Crash

### Loader

Forge

### Loader Version

Forge 43.1.55

### Mod Version

comforts-forge-6.0.3+1.19.2

### Relevant Log Outputs

Crash Report: https://mclo.gs/QFIdqMG

Latest Log: https://mclo.gs/T0n7SV7

**Comment by TheIllusiveC4** [comment]
Delete your Comforts configuration file and then try again.

**Comment by ChilledNyx** [comment]
Deleting the config file fixed it, thank you!
