### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by BloodshotPico** [TheIllusiveC4/Comforts#106]
### Minecraft Version

1.19.3

### What happened?

Installed the mod and get a dependency crash.

### How do you trigger this bug?

1. Make new MultiMC instance.
2. Install said mod.
3. Can't find SpectreLib-Forge

### Loader

Forge

### Loader Version

Forge - 44.0.18

### API Version

N/A

### Mod Version

Comforts-forge-6.1.0+

### Relevant Log Outputs

https://hastebin.com/oyedotejec.sql

**Comment by TheIllusiveC4** [comment]
Forge issue, update Forge to the latest version.
