### ISSUE TITLE
[Feature]: Punish those who keep awake for some days.

### ISSUE THREAD

**Issue by HySand** [TheIllusiveC4/Comforts#109]
### What is the new feature or improvement?

Add debuffs to those who don't sleep for some days, buff players after sleeping. I tried bettersleeping but just as #108 mentioned, they are imcompatible more or less. It will be awsome if comforts become an all in one mod.

**Comment by TheIllusiveC4** [comment]
As stated in the other issue, this would also be outside the scope of the mod as I'm not interested in introducing any additional sleeping mechanics outside of those specific to the sleeping bags and hammocks.
