### ISSUE TITLE
[Feature]: Only place sleeping bag when sleepable

### ISSUE THREAD

**Issue by ModProg** [TheIllusiveC4/Comforts#110]
### What is the new feature or improvement?

Only place the sleeping bag when you could actually sleep.

To just place the bag hold `<Shift>`.

**Comment by TheIllusiveC4** [comment]
The current behavior is how I intend it, which is:

1. If you want to attempt to sleep, you use it normally.
2. If you just want to place the bag, you hold shift and then place it.

This feature would introduce a third state and I don't think it would fit in as cleanly as the current behavior.

**Comment by ModProg** [comment]
> 1. If you want to attempt to sleep, you use it normally.

Yeah I wanted to keep that, but not place the sleeping bag when it is day but just print the message that you cannot sleep.

> 2. If you just want to place the bag, you hold shift and then place it.

I meant shift, github markdown hid the word for some reason.

**Comment by TheIllusiveC4** [comment]
> Yeah I wanted to keep that, but not place the sleeping bag when it is day but just print the message that you cannot sleep.

Oh wait, I understand now. Hmm...I'll think on it.

**Comment by ModProg** [comment]
One could hint that "you can hold <Shift> to place anyway".
