### ISSUE TITLE
[Feature]: Sleep by a campfire to set spawn

### ISSUE THREAD

**Issue by Slatebreaker** [TheIllusiveC4/Comforts#113]
### What is the new feature or improvement?

Sleeping in a sleeping bag when in proximity to a campfire could set the player's spawn. This would make exploration with sleeping bags super fun as you could setup campsites as you go for temporary respawn points.

The respawn point could be anchored to the sleeping bag, or alternatively to the campfire itself, such that players can pick up their sleeping bag and leave the site with it and still benefit from the spawn from the campfire.

**Comment by TheIllusiveC4** [comment]
While this sounds like a neat idea, it seems like it would over-complicate the respawn system.

Right now, it's quite clear to players that the bed is their respawn point and nothing else will affect that. However, with this mechanic, players now have to remember where the last time they slept in a sleeping bag that happened to be near a campfire. In addition, if they want to NOT set a new (albeit temporary) spawn point, they have to now remember to specifically not set up a campfire nearby. Or break the sleeping bag, or break the campfire. It would additionally be frustrating if they forget about this, die, and end up in a location that they weren't expecting.

I also wouldn't be sure how to make this kind of mechanic clear to the player without doing something convoluted like sending them a message every time they slept near a campfire.
