### ISSUE TITLE
[Feature]: sleeping bag not change dirt path to dirt

### ISSUE THREAD

**Issue by VinceKezel** [TheIllusiveC4/Comforts#115]
### What is the new feature or improvement?

My feature request is to have the sleeping bag not make dirt when placed on a dirt path. I know it's minecraft's vanilla behavior to replace a dirt path with dirt when a block is placed on top of it,... but a sleeping bag feels like a lightweight temporary item that shouldn't reset existing dirt path.

**Comment by TheIllusiveC4** [comment]
I think it's best to keep the current behavior. I don't want to subvert player's expectations too much and the vanilla behavior is simply to replace dirt paths if the block placed is solid, which sleeping bags are. It's also not trivial to accomplish this and I don't think it's worth the extra effort.

**Comment by VinceKezel** [comment]
Fair points. Still gonna use this mod daily :)
