### ISSUE TITLE
[Bug]: Sleeping bags break with sleepingBagBreakage = 0.0

### ISSUE THREAD

**Issue by DeshiDesu** [TheIllusiveC4/Comforts#117]
### Minecraft Version

1.18.2

### What happened?

The sleeping bag breaks after every time you sleep even when sleepingBagBreakage is set to 0.0

### How do you trigger this bug?

1. Go to config and set sleepingBagBreakage to 0.0
2. Place down sleeping bag
3. Sleep
...

### Loader

Forge

### Loader Version

Forge 40.2.0

### Mod Version

comforts-forge-1.18.2-5.0.0.6.jar

**Comment by DeshiDesu** [comment]
Misinterpreted 😂 it was not a bug

**Comment by SkGirlUru** [comment]
The same thing happens to me... how do I fix it?
