### ISSUE TITLE
[Bug]: quilt server crash on startup due to mixin InvalidAccessorException

### ISSUE THREAD

**Issue by ghost** [TheIllusiveC4/Comforts#118]
### Minecraft Version

1.19.3

### What happened?

quilt server crash on startup due to mixin InvalidAccessorException:
No candidates were found matching sleepCounter:I in net/minecraft/class_1657 for #comforts:comforts.mixins.json:AccessorPlayer from mod comforts->@Accessor[FIELD_SETTER]::setSleepCounter(I)V [INJECT Applicator Phase -> #comforts:comforts.mixins.json:AccessorPlayer from mod comforts -> Apply Accessors ->  -> Locate -> #comforts:comforts.mixins.json:AccessorPlayer from mod comforts->@Accessor[FIELD_SETTER]::setSleepCounter(I)V]

### How do you trigger this bug?

1. Use quilt-installer 0.5.0 to install minecraft 1.19.3 server with quilt loader 0.18.3
2. install comforts-quilt-6.1.1+1.19.3 and QFAPI 5.0.0-beta.8 QSL 4.0.0-beta.12
3. start server

### Loader

Quilt

### Loader Version

Quilt 0.18.3

### API Version

QFAPI 5.0.0-beta.8 and QSL 4.0.0-beta.12

### Mod Version

comforts-quilt-6.1.1+1.19.3

### Relevant Log Outputs

[latest.log](https://github.com/illusivesoulworks/comforts/files/10905806/latest.log)

**Comment by calinado** [comment]
receiving the same issue. pretty much identical error log on 1.19.3 quilt
