### ISSUE TITLE
[Bug]: Does not auto sleep if sleeping bag replaced non-solid blocks (e.g. snow layers)

### ISSUE THREAD

**Issue by MarioSMB** [TheIllusiveC4/Comforts#119]
### Minecraft Version

1.18.2

### What happened?

If your sleeping bag replaces blocks when you place it (e.g. snow layers or grass), you will not be put into it automatically.

### How do you trigger this bug?

1. Place sleeping bag on ground covered in snow

### Loader

Forge

### Loader Version

40.1.0

### API Version

N/A

### Mod Version

5.0.0.6

**Comment by TheIllusiveC4** [comment]
This has been fixed on 1.19.x versions of Comforts. Unfortunately, the 1.18.2 version of Comforts is only receiving critical bug fixes at this point in time and this does not qualify so the fix will not be backported.
