### ISSUE TITLE
Suggestion/Request: Allow Hammocks to hang from ArchitectuerCraft pillars

### ISSUE THREAD

**Issue by Lethann** [TheIllusiveC4/Comforts#12]
Just as it says, ArchitectureCraft allows these awesome pillars and would work really well for things like indoor hammock setups. My house has an indoor atrium but having to put a huge block of wood just to hang the hammock is a bit of a bummer.

**Comment by TheIllusiveC4** [comment]
I'll have to think about this some more, but I may just remove the wood requirement altogether. It was nice for flavor, but seems too restricting considering that Minecraft is about making all sorts of builds.

**Comment by Lethann** [comment]
yea, I still use wood, but because it's just an overlay it doesn't register as wood.

**Comment by TheIllusiveC4** [comment]
You will be able to hang hammocks on ArchitectureCraft pillars now, among most other blocks. It doesn't really look that great since there's a gap between the pillars' bounding boxes and the rope and nail, but that's not really something I can fix unfortunately.
