### ISSUE TITLE
[Feature]: Config option for disable sleeping bag or hammock feature individualy

### ISSUE THREAD

**Issue by MilkissWhite** [TheIllusiveC4/Comforts#121]
### What is the new feature or improvement?

config option for
1. disable sleeping bag(craft and use both)
2. disable hammock + rope and nail(craft and use both)

 with this feature, it can help balancing server difficulty. for people who thinking sleeping bag or hammock is too powerful.
 but my personal reason is compatibility with "Additional Additions" mod. Additional Additions have "Rope" item. it can place against wall, more rope place make rope longer beneath. so it's basically ladder alternative.
 meanwhile, "Comfort" mod have "Rope and Nail" as part of hammock.
 this two items have similar name and similar recipe, and even similar item texture. but completly different usage. it's confusing which rope is for hammock, viceversa. for me, sleeping bag 1st, rope 2nd, hammock 3rd priority.

 my best hope is "Rope and Nail can use as Rope from Additional Additions mod", but I think it's too greedy hope. so, disable config for hammock will be enough solution for me.

**Comment by TheIllusiveC4** [comment]
> my best hope is "Rope and Nail can use as Rope from Additional Additions mod"

Can you explain what you mean by this? Do you mean you want to use the Rope and Nail from Comforts in place of the Additional Additions Rope for placing against walls as a ladder? Or do you want to use the Additional Additions Rope to place hammocks in Comforts? Or both?

**Comment by MilkissWhite** [comment]
sorry for my bad english.

my best hope was "use Rope and Nail in place of the Additional Additions Rope for placing against walls as a ladder", but after I heard your question, I think I hope both.

but I don't know how difficult or painful work it is because I have zero-knowledge about programming. so I just requested some on/off feature config option. I'm happy enough this case.

feel free to choose whichever is more interesting to you.

**Comment by DeimosJ** [comment]
I would also like the ability to disable hammocks day to night feature without disabling the sleeping bag also.
