### ISSUE TITLE
[Bug]:  Sleeping bags craft into Cable insulation from Ultimate Car Mod

### ISSUE THREAD

**Issue by sashaforever** [TheIllusiveC4/Comforts#123]
### Minecraft Version

1.19.2

### What happened?

 Sleeping bags craft into Cable insulation from Ultimate Car Mod

### How do you trigger this bug?

1. Vanilla Crafting Table
2. Recipe for sleeping bag
3. Produces the cables and not the sleeping bag
...

### Loader

Forge

### Loader Version

Forge 43.2.14

### API Version

N/A

### Mod Version

6.05.5+1.19.2

**Comment by TheIllusiveC4** [comment]
This is likely an issue of a recipe conflict. You will either need to change the recipe for one of the items or use a mod like Polymorph.

**Comment by sashaforever** [comment]
> This is likely an issue of a recipe conflict. You will either need to change the recipe for one of the items or use a mod like Polymorph.

Thank you. I downloaded Polymorph as suggested and it works great.
