### ISSUE TITLE
[Bug]: Sleeping bag sets spawn point 

### ISSUE THREAD

**Issue by ProsperCraft** [TheIllusiveC4/Comforts#124]
### Minecraft Version

1.20.1

### What happened?

Using a sleeping bag sets your spawn point, so when it pops back up when you die you are back at spawn.

Expected behavior,- Not reset your spawn point

### How do you trigger this bug?

1. wait till night
2. use the sleeping bag on the ground.
3.
...

### Loader

Forge

### Loader Version

forge/1.20.1-47.0.19

### Mod Version

comforts-forge-6.3.3+1.20.1

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this, using `comforts-forge-6.3.3+1.20.1` on Forge 47.0.19 for 1.20.1:

1) Sleep in a bed.
2) Wait until night.
3) Sleep in a sleeping bag.
4) Do `/kill`.
5) Spawn at the bed location.

Did you test this with _only_ Comforts installed? If so, can you provide more detailed reproduction steps? If not, please isolate any potential mod conflicts and test again.

**Comment by ProsperCraft** [comment]
Solved, this was caused by the Dusk mod.
