### ISSUE TITLE
[Bug]: Config doesn't work

### ISSUE THREAD

**Issue by B1adereaper** [TheIllusiveC4/Comforts#126]
### Minecraft Version

1.19.2

### What happened?

Tried to turn on well rested and add a debuff for the sleeping bag.
this is the code I used:
sleepingBagDebuffs = [tetra:exhausted;25;2]
once saved it reverts to a prior version.

I assume it is a compatibly issue

### How do you trigger this bug?

1.added config data 
2.rebooted server
3.config reset
...

### Loader

Forge

### Loader Version

Forge 43.2.20

### API Version

unknown

### Mod Version

Comforts 6.05

**Comment by TheIllusiveC4** [comment]
You've formatted it incorrectly. It should be `["tetra:exhausted;25;2"]`. Note the quotation marks around the entry.
