### ISSUE TITLE
FMLCorePlugin issue?

### ISSUE THREAD

**Issue by Nexusdog** [TheIllusiveC4/Comforts#13]
This turned up in my log file - pertinent or useful?

[main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in comforts-1.12.2-1.1.0.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod

**Comment by TheIllusiveC4** [comment]
I'm aware, it's just a recommendation rather than a real warning. It shouldn't have any effect on gameplay. I'm hoping to do some rewrites when 1.13 comes that will stop this error from popping up.

**Comment by Nexusdog** [comment]
Okay, thanks for the heads up.
