### ISSUE TITLE
Tent [Feature]: 

### ISSUE THREAD

**Issue by CurseMeSilly** [TheIllusiveC4/Comforts#131]
### What is the new feature or improvement?

a small tent that protects you from mobs while you sleep or maybe you gives some sort of bonus, or a temporary spawnpoint (if that's possible to make). could be made as a separate item or an upgrade to the existing sleeping bag, idk i just really want something in the game that cat act as a quick shelter for the night while traveling and all these camping mods have all this extra stuff that i dont want. you already made sleeping bags, why not tents to make traveling just that bit more comfortable?

**Comment by TheIllusiveC4** [comment]
I'm not particularly interested in adding tents at this time. I might revisit this one day, but I'd rather just focus on enhancing the existing features if anything at the moment.
