### ISSUE TITLE
[Bug]: Unable to make sleeping bags

### ISSUE THREAD

**Issue by Lord-of-Lightning** [TheIllusiveC4/Comforts#137]
### Minecraft Version

1.20.2

### What happened?

While I was trying to make a backpack with the Travelers Backpack mod, with it you need to make a sleeping bag and it has the same recipe, so I am unable to make a backpack

### How do you trigger this bug?

1.
2.
3.
...

### Loader

Fabric

### Loader Version

Fabric 1.20.1

### API Version

Fabric API

### Mod Version

6.3.4 + 1.20.1

**Comment by TheIllusiveC4** [comment]
Recipe conflicts are not bugs and need to be solved through external methods if used with other mods that use the same recipe. These can be solved either through datapacks or a recipe conflict mod such as [Polymorph](https://modrinth.com/mod/polymorph).
