### ISSUE TITLE
[Bug]: Crash on startup

### ISSUE THREAD

**Issue by NolanHewitt** [TheIllusiveC4/Comforts#139]
### Minecraft Version

1.20.1

### What happened?

Crash on startup

### How do you trigger this bug?

Start the game

### Loader

Quilt

### Loader Version

0.23.1

### API Version

QFAPI 7.5.0

### Mod Version

Comforts-quilt-6.3.5+1.20.1

### Relevant Log Outputs

https://gist.github.com/NolanHewitt/edd86f4bff8eb743a0f2514e3bde6f0a

**Comment by NolanHewitt** [comment]
nevermind, this was caused by me using a fabric version of the vein mining mod instead of the quilt version.

**Comment by TheIllusiveC4** [comment]
I'll keep this open so that I can remember to investigate cross-compatibility between using Fabric and Quilt versions of the embedded library.
