### ISSUE TITLE
[Feature]: Update sleeping bag recipe

### ISSUE THREAD

**Issue by smohara1986** [TheIllusiveC4/Comforts#146]
### What is the new feature or improvement?

Love the mod, but would love the sleeping bag recipe to be updated. Currently it follows the format of making a half slab. This ends up clashing with mods such as "More Slabs Stairs & Walls" ([Modrinth](https://modrinth.com/mod/more-slabs-stairs-and-walls) page, and [source](https://github.com/Nibaru/More-Slabs-Stairs-and-Walls)) which add in the wool half slabs.

![wool-half-slab](https://github.com/illusivesoulworks/comforts/assets/94147431/cbc72a68-56ed-42d2-b3d9-5cc5768dabf4)

If instead the recipe was updated so that the wool went up and down, then it would still make sense as a recipe and be compatible with wool half slabs. I don't believe it's necessary, but if you wanted to be extremely picky, you could even rotate the inventory icon 90 degrees. That would allow the icon to be in the same orientation as the recipe.

![updated-sleeping-bag](https://github.com/illusivesoulworks/comforts/assets/94147431/26a03202-3cfa-4216-b4f2-bed9610b7c6c)

**Comment by notIkibo** [comment]
If you have a lot of mods, they eventually end up clashing with each other. A simple solution would be adding the Polymorph mod. It gives you the opportunity to switch whichever endproduct you desire

**Comment by TheIllusiveC4** [comment]
> If you have a lot of mods, they eventually end up clashing with each other.

While this is true, and something to keep in mind with modded Minecraft in general, I've decided to accommodate this request regardless. The slab recipe shape is well-known and the idea of a wool slab is not uncommon and will always conflict with Comforts's chosen recipe for its sleeping bags. There's nothing to be lost by changing the recipe to a vertical orientation to avoid this happening, now and in the future.
