### ISSUE TITLE
[Bug]: Mod Crashes on Newer NeoForge Builds

### ISSUE THREAD

**Issue by ModernGamingWorld** [TheIllusiveC4/Comforts#149]
### Minecraft Version

1.20.6

### What happened?

![2024-06-02_21 21 27](https://github.com/illusivesoulworks/comforts/assets/75923060/6b71a882-34d2-4132-8ce9-37b3599e22ba)

### How do you trigger this bug?

1. use my custom modpack
2. update NeoForge
3. Boom Big Crash
...

### Loader

NeoForge

### Loader Version

Neoforge - 20.6.100

### Mod Version

comforts-neoforge-8.0.0+1.20.6-3.3

### Relevant Log Outputs

![2024-06-02_21 21 27](https://github.com/illusivesoulworks/comforts/assets/75923060/92a1b62f-6885-4cd6-b1c1-e9cd4c495739)

**Comment by ilQueen** [comment]
Same updated my server to 1.20.6.100 and it crashes my server now
