### ISSUE TITLE
[Bug]: Mod fails to load due to undefined operation error

### ISSUE THREAD

**Issue by Ayyavazi** [TheIllusiveC4/Comforts#150]
### Minecraft Version

1.20.6

### What happened?

While trying to load Minecraft with mod installed, it fails to load, throwing attached error

### How do you trigger this bug?

1.Load Curseforge client
2.Select Play Modpack - Experimental (self-created)
3.Click Play on the Minecraft Launcher
4. Bug occurs during loading
...

### Loader

NeoForge

### Loader Version

Neoforge 20.6.100

### Mod Version

Comforts-neoforge-8.-.-+1.20.6

### Relevant Log Outputs

![image](https://github.com/illusivesoulworks/comforts/assets/171757711/4e3e7563-9c31-4ca8-b9cc-1f2a2830247c)

**Comment by TheIllusiveC4** [comment]
You need to update Comforts to 8.0.1+1.20.6.

**Comment by Ayyavazi** [comment]
Thanks, I thought I had. For some reason the update button in Curseforge reverts you to the older version.
