### ISSUE TITLE
[Bug]: daySleepingPercentage set to 0 does not skip the night

### ISSUE THREAD

**Issue by thomwoosley** [TheIllusiveC4/Comforts#154]
### Minecraft Version

1.20.1

### What happened?

I've set daySleepingPercentage=0 as the config says to, which should skip the night when any single person sleeps.  Skipping the night does not happen.

Interestingly, sleeping in a hammock will skip the day for everyone.  So, that part works.

### How do you trigger this bug?

1. Log on at least two players.
2. Sleep in a sleeping bag or bed with one player.
3. Nothing is skipped.
...

### Loader

Forge

### Loader Version

Forge 47.3.5

### Mod Version

Comforts 6.4.0

**Comment by TheIllusiveC4** [comment]
This is working as intended. `daySleepingPercentage` is only for skipping the day. The configuration for skipping the night is the same as vanilla, which is set by the `sleepingPercentage` gamerule.
