### ISSUE TITLE
[Bug]: net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'spectrelib'!

### ISSUE THREAD

**Issue by Rhazio** [TheIllusiveC4/Comforts#159]
### Minecraft Version

1.20.1

### What happened?

Trying to launch Fabric server from my PC. The server won't launch and instead crash. 

I hadn't launched this server since August as I have another Forge server I run for my friends. We wanted to go back to the Fabric one but now this is occurring. 

There are some other mods causing the issue, so I disabled them and this is still happening. I have tried deleting the config file inside the `config` folder but it still persists 

### How do you trigger this bug?

1. Launch server with Comforts in the mod folder
2. Crash

### Loader

Fabric

### Loader Version

0.15.7

### API Version

0.92.0

### Mod Version

6.4.0

### Relevant Log Outputs

https://pastebin.com/gCDxLMTV

**Comment by TheIllusiveC4** [comment]
This looks like potentially some mismatched versions of mods in your folder. Can you share the entire crash log?

**Comment by Rhazio** [comment]
Yes, here is the whole crash log https://pastebin.com/TFc0hjX7

I am having issues with another mod causing the crash but comforts is one of them

**Comment by TheIllusiveC4** [comment]
I think this is caused by using Java 23. For 1.20.1, you should downgrade to Java 17 (other versions may be compatible, I'm not sure, but I know 17 works for sure).

**Comment by Rhazio** [comment]
Is there a way to verify that I successfully downgraded after installing Java 17?

**Comment by Rhazio** [comment]
Nevermind, got it to downgrade to Java 17. The server now launches from the looks of it. No issues that I can see at the moment. Thank you for the help :)
