### ISSUE TITLE
Hammock sets time of day wrong

### ISSUE THREAD

**Issue by Darkmega18** [TheIllusiveC4/Comforts#19]
As you requested, new issue directly for the issue.
https://github.com/TheIllusiveC4/Comforts/issues/18#issuecomment-417311601
To rehash it, the hammock is instead awkwardly setting time to day instead of night. I have a few other bed like mechanics in my pack, so I'm not sure if they could be interacting weirdly with it as I said. but my Modpack is called "Transcendence" if you'd like to get a modlist of things to investigate.

As I mentioned a cyclic item based bedroll exists, openblocks sleeping bag exists, your sleeping bags exist, and so does a "bed pet" that has the power to spawn a bed pet minion you interact with to "sleep" that sets time to day and such. I think quark might also have some kind of morpheus sleep democracy thing going on too.

**Comment by TheIllusiveC4** [comment]
Can you try it with either Comforts version 1.2.0.1 or 1.3.0 (depending on which Forge version you have)? I pushed out these updates yesterday that I think might address your problem.

**Comment by Darkmega18** [comment]
Yes, I gained that version last night but was in a hurry to finish my quests and update my pack then. I'll try it on the server promptly when my game finally loads and give the verdict. :)

**Comment by Darkmega18** [comment]
Ok, yeah, with the forge update and the new version the hammock works fine now. :D yay! slow responses cause played for a time, had dinner, played another game, came back, realized I hadn't said anything yet. :V
