### ISSUE TITLE
Server crash at start with Comforts 0.0.8 (RC1)

### ISSUE THREAD

**Issue by Hund** [TheIllusiveC4/Comforts#2]
I just updated to Comforts Comforts 0.0.8 (RC1) on my server and it just crashes at start. It worked just fine on my client though.

Log: [crash-2017-11-13_03.39.14-server.txt](https://github.com/TheIllusiveC4/Comforts/files/1465451/crash-2017-11-13_03.39.14-server.txt)

**Comment by TheIllusiveC4** [comment]
Oh that's no good. I'll work on a fix right away.

**Comment by TheIllusiveC4** [comment]
I've just pushed out a new update, 0.0.8-rc2, that should fix this issue. It'll be available as soon as CurseForge approves it. Thank you very much for submitting this issue and please let me know if the problem continues.

**Comment by Hund** [comment]
Thank you! :)
