### ISSUE TITLE
[suggestion] Punishment to players that don't sleep

### ISSUE THREAD

**Issue by wenlfs** [TheIllusiveC4/Comforts#20]
Apply some punishment for players that don't sleep for some days in a row could stimulate the player to sleep to avoid debuffs. It could be potions effects or even death as an extreme punishment, so in death case when the player reach a limit of days without sleep they get damage till die.

**Comment by TheIllusiveC4** [comment]
While an interesting idea, this is largely what the Phantoms in 1.13 are used for and I don't really want to introduce a feature that will be obsoleted in the very next version. In addition, adding this sort of sleep deprivation punishment system is a little outside the scope of this mod.
