### ISSUE TITLE
Crash when player slept in cryogenic chamber from Galacticraft

### ISSUE THREAD

**Issue by DWX12** [TheIllusiveC4/Comforts#23]
Had a crash report pop up when a player slept in a cryo bed from Galacticraft:

https://paste.dimdev.org/fonibaxoxi.mccrash

I have the most recent versions of both GC (GalacticraftCore-1.12.2-4.0.1.181) and Comforts (comforts-1.12.2-1.4.1).

**Comment by TheIllusiveC4** [comment]
Hm, doesn't crash for me. At least in the Overworld. Where were you sleeping when this crash happened?

**Comment by TheIllusiveC4** [comment]
Still couldn't reproduce it, but made some changes that may solve the issue regardless.

**Comment by DWX12** [comment]
Thank you for the response. I think I might be getting these issues with other mods too. Sometimes they pop up as unknown and other times the crash reports point to other mods.

I'm using VanillaFix, so they aren't game breaking, as far as I can tell. I'm able to keep playing and they don't seem to be actually doing anything negative. I am; however, getting some graphical issues from time to time, which is probably due to Optifine in addition to other mods.

Again, thank you and I will try to send you more info, or atleast some more crash reports, if anything else happens.
