### ISSUE TITLE
crashes upon world load 1.13.2

### ISSUE THREAD

**Issue by duntwave** [TheIllusiveC4/Comforts#26]
#### Versions (Be specific, do not write "latest"):
* Comforts: 1.13.2-2.0-beta1
* Forge: 25.0.198
#### Steps to Reproduce:
1. start game lol 
2. join world 
3. crash
...

Crash Log: https://hastebin.com/akumipuvas.coffeescript

**Comment by TheIllusiveC4** [comment]
Can you reproduce this without any other mods? This is a common error when any mod in the mod list returns null in a capability.

**Comment by TheIllusiveC4** [comment]
@duntwave Following up on this again, can you reproduce this bug without any other mods?

**Comment by TheIllusiveC4** [comment]
Closing this for lack of information and follow-up. Feel free to comment with a follow-up at any time and I'll re-open the issue.
