### ISSUE TITLE
Mod incompatible with any Forge newer then 2772

### ISSUE THREAD

**Issue by scienceman217** [TheIllusiveC4/Comforts#27]
[2019-06-05-6.log.gz](https://github.com/TheIllusiveC4/Comforts/files/3259510/2019-06-05-6.log.gz)

* Comforts: 1.3.1
* Forge: 2773
#### Steps to Reproduce: 
1. Install Comforts and Forge 2773+
2. Click Launch Game

**Comment by TheIllusiveC4** [comment]
You're using an old version of Comforts, updating to the latest 1.4.1.2 version should solve the issue.
