### ISSUE TITLE
[Bug] ver. 1.0.0 incompatible with Morpheus

### ISSUE THREAD

**Issue by Luke616** [TheIllusiveC4/Comforts#3]
Title, when I updated Comforts to v1.0.0 this crash occurred:
https://pastebin.com/amaJePKP

The crash to be morpheus related but I can confirm this did not occur with comforts v0.0.8. Is this on your end?

Thanks!
Luke616

**Comment by TheIllusiveC4** [comment]
Yep, this is on my end. I forgot to test this before releasing, my apologies. I pushed out a new update, version 1.0.0.1, that should fix this issue. It's just awaiting Curse approval.

**Comment by Luke616** [comment]
You're quick! Thanks a bunch
