### ISSUE TITLE
Suggestion: Backpacks

### ISSUE THREAD

**Issue by SepSol** [TheIllusiveC4/Comforts#34]
Currently there are no good backpack mods for 1.14.4 (Forge). It would be nice if we had something like '[Wearable Backpacks](https://www.curseforge.com/minecraft/mc-mods/wearable-backpacks)' mod in this version. 

As for why I want this feature:

- Makes carrying items around so much easier
- Adds new possibilities in multiplayer gameplay as people can borrow things from each others' backpacks
- It has nice animations for opening and closing backpacks
- And it's a neat portable storage :) I am probably just spamming this section, but you get what I mean.

**Comment by TheIllusiveC4** [comment]
While I think this is a fair suggestion in general, this doesn't really belong here since Comforts is mainly just focused around beds/sleeping.
