### ISSUE TITLE
Allow Blocks to be Waterlogged

### ISSUE THREAD

**Issue by WenXin20** [TheIllusiveC4/Comforts#36]
**Please describe the new feature or change.**
Allow blocks, such as sleeping bags, hammocks, and rope & nails, to be watelogged.

**Please describe why you want this feature.**
This would allow for new decoration options.

**Comment by TheIllusiveC4** [comment]
Is this purely decorative or were you hoping to be able to sleep in them when waterlogged as well?

**Comment by WenXin20** [comment]
Probably only decorative
