### ISSUE TITLE
Leisure Hammock Bug

### ISSUE THREAD

**Issue by ElvenChaos** [TheIllusiveC4/Comforts#38]
#### Versions (Be specific, do not write "latest"):
* Comforts: 1.4.1.2
* Forge: 14.23.5.2847
#### Observed Behavior: When both the "leisure hammock" setting is on and Sponge Forge is installed, using the hammock for leisure makes it get stuck as "occupied" for if you wanted to sleep in it to pass the day.

Breaking and replacing the hammock fixes the issue when just these mods are installed, though I came across this part of the problem trying to hunt down a nastier version of the bug where breaking and replacing the hammock doesn't fix the issue and the sleep feature was only usable once, ever. As of writing I'm still trying to narrow that version down for a separate bug report.
#### Steps to Reproduce:
1. Install Sponge Forge (1.12.2-2838-7.1.8) and Comforts
2. Enable Leisure Hammocks settings in configs
3. "Sit" in hammock then dismount.
4. Try to sleep in hammock, "Hammock is occupied"

Crash Log: None.

Sorry in advance if this is a sponge bug and not a comforts bug.

**Comment by TheIllusiveC4** [comment]
I'm not 100% sure because I'm not too familiar with SpongeForge, but I believe this is a bug on their end. It seems like they're not processing the EntityMountEvent correctly, since that houses the logic for killing the placeholder resting "chair" and setting the occupied value to false.
