### ISSUE TITLE
Not allowing to respawn player in 1.12 with sponge.

### ISSUE THREAD

**Issue by Raycoms** [TheIllusiveC4/Comforts#4]
Newest spongeforge version with newest comfort version with best forge for that spongeforge
https://cdn.discordapp.com/attachments/372264384690388992/381436589601062914/image.png

**Comment by TheIllusiveC4** [comment]
I've successfully replicated the bug. I'll see what I can do, this is my first time working with SpongeForge so it might take a while.

**Comment by ryantheleach** [comment]
@TheIllusiveC4 If you are going to be debugging in a SpongeForge environment and use IntelliJ I **highly** recommend installing https://github.com/minecraft-dev/MinecraftDev It provides debugging support for mixins that would otherwise be painful.

**Comment by TheIllusiveC4** [comment]
@ryantheleach Thank you for informing me of that, I was unaware.

**Comment by ryantheleach** [comment]
If you are using windows as well, you may need to use the nightly release as a pretty major bug was fixed in build 69. if when you install it you get a version before 69, you can switch to the nightly releases in the settings.

![image](https://user-images.githubusercontent.com/141554/32982774-b09e7376-ccd9-11e7-8816-1b9b6817516a.png)

**Comment by TheIllusiveC4** [comment]
I'm pushing out a new update on CurseForge, version 1.0.0.2, that should address this issue. I added a simple null check in the appropriate method that should stop this problem from happening.

**Comment by ryantheleach** [comment]
@TheIllusiveC4 Is the forge event for setSpawn non nullable or is null allowed? If it's non-nullable I'll create a ticket on SpongeCommon to fix it

**Comment by TheIllusiveC4** [comment]
Null is allowed as far as I'm aware, it's just that Forge never passes a null argument so I never encountered this problem in a solely Forge environment.
