### ISSUE TITLE
Config not available

### ISSUE THREAD

**Issue by ghboyek** [TheIllusiveC4/Comforts#41]
#### Versions (Be specific, do not write "latest"):
* Comforts: FORGE-1.14.4-2.0-beta6
* Forge: 28.2.3
#### Observed Behavior:
No comforts.toml found in config folder
#### Expected Behavior:
comforts.toml in config folder
#### Steps to Reproduce:
1. Launch 1.14.4 with comforts installed.
2. Look in config folder.
...

Crash Log: N/A

**Comment by TheIllusiveC4** [comment]
It's a server-side config. You need to look into your world save in the `serverconfig` folder.
