### ISSUE TITLE
Unclear how to format `sleepingBagDebuffs`; suggest more detailed description in the wiki?

### ISSUE THREAD

**Issue by nepphhh** [TheIllusiveC4/Comforts#43]
```
#Format: [effect] [duration(secs)] [power]
sleepingBagDebuffs = [minecraft:mining_fatigue] [60] [1]
```

This does not properly load. Other similar variations also fail to load. Peering through [the source](https://github.com/TheIllusiveC4/Comforts/blob/7f981a16f844d20507012a4b5d6e0487db3de0dd/src/main/java/top/theillusivec4/comforts/common/ComfortsConfig.java#L80) doesn't make it any more obvious to me, a non-modder.

Perhaps the configuration format should be explained a bit more explicitly, maybe on the wiki?

**Comment by TheIllusiveC4** [comment]
Sure, sorry about the vagueness. It's hard to delineate clearly when I'm biased, being the modder and all.

Here's an example that should clear up the confusion:
```
sleepingBagDebuffs = ["minecraft:mining_fatigue 60 1", "minecraft:weakness 30 1"]
```
This will add two effects to the list. The list itself is defined by the brackets. Each entry is separated by commas. Each entry needs to be wrapped by quotation marks. Each option in the entry is separate by a space.

I've also added this to the wiki for future reference.

**Comment by nepphhh** [comment]
Thank you!
