### ISSUE TITLE
hammock sleep bug

### ISSUE THREAD

**Issue by Warbringer12** [TheIllusiveC4/Comforts#45]
tried sleeping in hammock
#### Versions (Be specific, do not write "latest"):
* Comforts: 1.16.2-4.0.0.0
* Forge: 33.0.20
#### Steps to Reproduce:
1. right click hammock at night
2.
3.
...
![2020-08-25_09 52 52](https://user-images.githubusercontent.com/44590540/91204767-653c2480-e6b9-11ea-975a-fc7a7a2afbc6.png)

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/). no crash report

**Comment by TheIllusiveC4** [comment]
As the message you got in the screenshot states, you can only sleep in hammocks during the day. They turn day to night.
