### ISSUE TITLE
Hammock breaks if more than 1 player are on a server

### ISSUE THREAD

**Issue by DreiPixel** [TheIllusiveC4/Comforts#50]
#### Versions (Be specific, do not write "latest"): 
* Comforts: 4.0.0.3
* Forge: 35.1.15
#### Observed Behavior: 
Hammock skips to the next day if there are more than 1 player on a server
#### Expected Behavior: 
Hammock working with any amount of players on a server
#### Steps to Reproduce:
1. Use hammock on a server with more than 1 player.

I have no idea if this is confict with a mod. the only mod i can imagine being Morpheus (sleep vote mod)

**Comment by TheIllusiveC4** [comment]
I believe this is a conflict with Morpheus, as that mod doesn't use one of the Forge hooks that allows other mods to manipulate the time skip logic. It skips to day because Morpheus is assuming full control of the time skip.
