### ISSUE TITLE
Make dye mechanics consistent with vanilla

### ISSUE THREAD

**Issue by FewerFlaws** [TheIllusiveC4/Comforts#51]
**Please describe the new feature or change.**
1. Any color of sleeping bag or hammock should interact with dye to take a new color
2. White dye and bonemeal should dye a sleeping bag or hammock white.

**Please describe why you want this feature.**
To be consistent with the vanilla dye mechanics related to beds.

**Comment by TheIllusiveC4** [comment]
The way your request is phrased implies that vanilla beds operate this way. I just tested this and that's not the case. I can only dye white beds, and dyed beds cannot be dyed back to white.

This is also consistent with what the Minecraft wiki says, specifying that the proposed behavior is not available on the Java edition:
https://minecraft.gamepedia.com/Bed#Crafting

Have you tested a fresh, vanilla instance to verify your expectations?

**Comment by FewerFlaws** [comment]
I just did and you are correct.  My apologies.  I will make the change on my end =]

**Comment by FewerFlaws** [comment]
Honestly, by "make the change" I mean that I'll figure out which mod thinks you can dye black things white and whip it into shape ;)
