### ISSUE TITLE
CTD Error When Trying to Place Hammocks

### ISSUE THREAD

**Issue by ItsCliffGaming** [TheIllusiveC4/Comforts#53]
Anytime I attempt to place a hammock, I crash to desktop, with the following error message:

`The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot set property DirectionProperty{name=facing, clazz=class net.minecraft.util.Direction, values=[north, south, west, east]} to up on Block{comforts:hammock_white}, it is not an allowed value
Exit Code: -1`

Full crash report posted.

[crash-2021-03-21_04.05.46-client.txt](https://github.com/TheIllusiveC4/Comforts/files/6177034/crash-2021-03-21_04.05.46-client.txt)

**Comment by TheIllusiveC4** [comment]
How are you placing the hammock? Please list your steps as detailed as possible. In addition, can you reproduce this with only Comforts installed?

**Comment by ItsCliffGaming** [comment]
Thanks for the prompt response. So, Anytime I right click the ground with a hammock it does it. There are no more specifics to it, literally any time. Now, with that being said, I cannot duplicate the error in single player, only in multiplayer, so I cannot easily test removing all the mods in that environment. But, even with all the mods, I don't get any errors in the Single Player world. I will try and start up a server on my local machine to see if I can duplicate it in that environment.
