### ISSUE TITLE
Hammock turns it to daytime sometimes

### ISSUE THREAD

**Issue by Thezapman1** [TheIllusiveC4/Comforts#57]
I right-click to sleep in the hammock and sometimes (about half the time I've tried) it turns it to daytime, however, if I manually set the time to 1000 let's say, and then sleep, it guarantees that it will turn it to nighttime as it should. I'm on the latest version 1.16.5 using the mod's latest version. I'm currently playing on the ATM6 mod pack, with a few extras added of my own.

**Comment by TheIllusiveC4** [comment]
I've tried a few times but unfortunately I cannot reproduce this issue. I can only assume at this juncture that it's a mod conflict. I suspect that perhaps a mod is changing the daytime of the game in such a way that it interferes with the hammock's time changing logic.

**Comment by NielsPilgaard** [comment]
I've had a report of this as well: It seems to happen when the mod Morpheus (only a percentage of players need to sleep-mod) makes sleep "successful".

There's a good video showing the issue in the E6 bug report.
https://github.com/NillerMedDild/Enigmatica6/issues/2241
https://github.com/Quetzi/Morpheus/issues/94
