### ISSUE TITLE
When ever you install the mod an error appears

### ISSUE THREAD

**Issue by GamingNerdLeith** [TheIllusiveC4/Comforts#64]
#### Versions (Be specific, do not write "latest"):
* Comforts (comforts-forge-1.16.5-4.0.1.1.jar)
* Forge (36.1.32)
* 1.16.5
#### Observed Behavior:
![error](https://user-images.githubusercontent.com/67237948/125358881-6d4c9380-e361-11eb-9f8b-6687b7c9e371.png)
#### Expected Behavior:
Load to main menu after launching minecraft
#### Steps to Reproduce:
1. Download forge
2. drag comforts-forge-1.16.5-4.0.1.1.jar to mods folder
3. launch the game
#### Crash/Debug Logs:
[debug.log](https://github.com/TheIllusiveC4/Comforts/files/6804492/debug.log)
[latest.log](https://github.com/TheIllusiveC4/Comforts/files/6804493/latest.log)

**Comment by TheIllusiveC4** [comment]
It looks like some mod called Golden Age Combat is causing a mixin injection error while Comforts is loading. Have you tried removing that mod?

**Comment by GamingNerdLeith** [comment]
It fixes that issue, sorry to bother you with a bug report.
