### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by Razer7000** [TheIllusiveC4/Comforts#66]
#### Versions (Be specific, do not write "latest"):
* Comforts: 5.0.0.0
* Forge/Fabric: 37.0.18
#### Steps to Reproduce:
1. 
2.
3.
...

Crash/Debug Logs: Please see [how to share logs](https://fabricmc.net/wiki/player:tutorials:logs_ml:windows#how_to_post_your_logs_to_get_help).
[crash-2021-08-05_10.45.52-client.txt](https://github.com/TheIllusiveC4/Comforts/files/6942380/crash-2021-08-05_10.45.52-client.txt)

**Comment by TheIllusiveC4** [comment]
Update to Forge 37.0.19 or higher.

**Comment by Razer7000** [comment]
thx
