### ISSUE TITLE
Hammock moving time forward too much

### ISSUE THREAD

**Issue by Muffintiem** [TheIllusiveC4/Comforts#68]
I am currently using the latest version of Comforts for Fabric on Minecraft version 1.17.1. I installed a mod that adds a calendar and I've discovered that sleeping in the hammock will make it the next day. So it is like I'm waking up at sunset of the next day. I don't think this is desired behavior since if I use both the sleeping bag and the hammock time will move twice as fast.

**Comment by TheIllusiveC4** [comment]
What's the mod that adds a calendar? Just so I can reproduce it for testing.

**Comment by Muffintiem** [comment]
It's Enhanced Celestials. There's a command to call up a calendar of upcoming lunar events and how many days away they are. After sleeping in the hammock the number of days changes when it should only change with the sleeping bag.
