### ISSUE TITLE
Unable to leave cot

### ISSUE THREAD

**Issue by Sixty9ing** [TheIllusiveC4/Comforts#70]
I had to force shut down the application after getting into my cot and being unable to leave, open any menu, or use commands.

**Comment by Sixty9ing** [comment]
Just thought I would report that happening, I have other mods installed aswel and wasn't able to re create it thankfully, however the cot after re-starting said it was occupied and I broke and re placed it before trying.

**Comment by TheIllusiveC4** [comment]
Since I haven't gotten any other reports and you weren't able to reproduce it, I will just call this a weird one-time error.
