### ISSUE TITLE
Leisure hammocks on Fabric version

### ISSUE THREAD

**Issue by Colear** [TheIllusiveC4/Comforts#72]
I can't find the leisureHammocks option, which is in the documentation, in the Fabric 1.18 configuration, is this normal? If so, will this option be implemented later?

PS. Thanks for this great mod.

**Comment by TheIllusiveC4** [comment]
Unfortunately, Leisure Hammocks are a legacy feature that was removed a long time ago and I do not currently have plans to re-implement it.
