### ISSUE TITLE
Crash when trying to start the game

### ISSUE THREAD

**Issue by muhammedesadcomert** [TheIllusiveC4/Comforts#74]
#### Versions:
* comforts-fabric-1.0.2-1.18.1
* Fabric - 0.13.3
* Game version: 1.18.2
#### Expected Behavior: Successful start of the game

Crash Logs: https://pste.ch/iropebowoq.rb

**Comment by kingstairs** [comment]
Confirming with a clean MC instance (MultiMC) - reproducible.
Crash Log: [comforts-crash-20220307.txt](https://github.com/TheIllusiveC4/Comforts/files/8202370/comforts-crash-20220307.txt)
.

**Comment by TheIllusiveC4** [comment]
Should be now fixed in 1.1.0-1.18.2.
