### ISSUE TITLE
Server Crash on 1.18.1 Forge 39.1.0

### ISSUE THREAD

**Issue by Slickson77** [TheIllusiveC4/Comforts#79]
#### Versions (Be specific, do not write "latest"):
* Comforts: comforts-forge-1.18.1-5.0.0.2.jar
* Forge/Fabric: Forge 39.1.0
* 
#### Observed Behavior: Server Crashes when you place down a sleeping bag (and can't sleep in it because it is day time or a monster is near forcing the bag to not auto break).  When this happens and you manually break the bag ... Server go boom.

This doesn't seem to happen in single player worlds.  I made a copy of the server, deleted all the configs, mods, and even the world folder.  I only left the Comforts mod ... just as you specified, there are no other mods on the server and it still go boom.

#### Steps to Reproduce:
1.Set time to day
2.Place sleeping bag on ground
3.Break sleeping bag
4.Server go boom
...

Crash/Debug Logs: Please see [how to share logs]
[crash-2022-03-12_22.36.03-server.txt](https://github.com/TheIllusiveC4/Comforts/files/8238938/crash-2022-03-12_22.36.03-server.txt)

**Comment by TheIllusiveC4** [comment]
Your server is running on 1.18.1, which does match the version you listed above. However, if I look at your crash log, it says:

> comforts-forge-1.18.2-5.0.0.3.jar 

Your server is running the 1.18.2 version of Comforts. You should downgrade to the 1.18.1 version.
