### ISSUE TITLE
Placing a sleeping bag when time to sleep makes arm stand up

### ISSUE THREAD

**Issue by Ayutac** [TheIllusiveC4/Comforts#80]
#### Versions (Be specific, do not write "latest"):
* Comforts: 1.1.2-1.18.2
* Fabric API: 0.47.10+ 1.18.2
#### Steps to Reproduce:
1. new world
2. wait for night
3. place down sleeping bag

**Comment by TheIllusiveC4** [comment]
Could you provide a screenshot of this happening?

**Comment by Ayutac** [comment]
![2022-03-25_19 43 49](https://user-images.githubusercontent.com/7873396/160182641-8613270d-6abc-4693-87b7-651f4e4367fb.png)
![2022-03-25_19 44 12](https://user-images.githubusercontent.com/7873396/160182644-823bd39e-dd4f-48cf-9b3f-50e9e6741e75.png)

First version is placing the bag while it is night.

Second version is placing the bag during the day and then go to bag in the night.

EDIT: Done on Minecraft 1.18.2 with Fabric API 0.47.10 and Comforts 1.1.2, flat peaceful creative world
