### ISSUE TITLE
Crash on start-up

### ISSUE THREAD

**Issue by ekiplier** [TheIllusiveC4/Comforts#81]
My modpack crashed and it indicates Comforts as the issue.

![image](https://user-images.githubusercontent.com/74121461/161794139-41dceb5d-6546-45ae-b84e-f81128ebe2f0.png)

Here's the crash report:
[crash-2022-04-05_16.43.22-fml.txt](https://github.com/TheIllusiveC4/Comforts/files/8419794/crash-2022-04-05_16.43.22-fml.txt)

**Comment by ekiplier** [comment]
Btw, I think this is already in the report, but I'll leave all the versions here just in case:

MC version - 1.16.5
Forge version - 36.2.33
Comforts version - forge-1.16.5-4.0.1.5

Edit: The mod loader and Comforts' versions are the latest ones currently available on the CurseForge launcher.

Edit2: After running my modpack without Comforts, the game was able to start, which confirms that this mod is (one of) the issue(s). Don't know if it helps, but here's the latest.log also:
[latest.log](https://github.com/TheIllusiveC4/Comforts/files/8419941/latest.log)

**Comment by TheIllusiveC4** [comment]
If you remove just Tough as Nails, is the game able to start?

**Comment by ekiplier** [comment]
Hi! thanks for your response. Yes, the game is able to start without TAN. Since I don't know whose side is able to fix it, I'll reference this issue on the TAN page. Thanks!

**Comment by TheIllusiveC4** [comment]
This actually isn't a Comforts issue, but it is (kinda) a Diet issue.
All further correspondence will be at the corresponding Diet thread:
https://github.com/TheIllusiveC4/Diet/issues/123
