### ISSUE TITLE
when you try to break a sleeping bag the game crashes

### ISSUE THREAD

**Issue by meganrosee** [TheIllusiveC4/Comforts#82]
#### Versions (Be specific, do not write "latest"):
* Comforts: 1.18.2 
* Forge/Fabric: forge
#### Steps to Reproduce:
1.
2.
3.
...

Crash/Debug Logs: Please see [how to share logs](https://fabricmc.net/wiki/player:tutorials:logs_ml:windows#how_to_post_your_logs_to_get_help).
[crash-2022-04-13_20.07.56-client.txt](https://github.com/TheIllusiveC4/Comforts/files/8485563/crash-2022-04-13_20.07.56-client.txt)

**Comment by TheIllusiveC4** [comment]
> comforts-1.18.2.jar                               |Comforts                      |comforts                      |1.18.1-5.0.0.2      |DONE      |Manifest: NOSIGNATURE

Your log shows that you're using Comforts for 1.18.1, which will not work properly in 1.18.2. Please update your Comforts version to the latest for 1.18.2.
