### ISSUE TITLE
[1.18.1] Server crash when sleeping bag was broken

### ISSUE THREAD

**Issue by WenXin20** [TheIllusiveC4/Comforts#84]
#### Versions (Be specific, do not write "latest"):
* Comforts: v5.0.0.2
* Forge: v39.1.2
#### Observed Behavior:
- The sleeping bag was broken, which caused a crash, even though this was not the first time the sleeping bag was broken.
- There was a rainstorm, and it showed the message that you can't sleep during a rainstorm, then it crashed when breaking it.

#### Expected Behavior:
- No crashes

#### Steps to Reproduce:
1. Place sleeping bag during a rainstorm
2. Right-click it
3. Break it
4. Crash

P.S. I'm not sure if the rainstorm was related.
...

[Latest Server Log](https://gist.github.com/WenXin20/5a8aaee3a9c45ad80808f775101bd9d7#file-latest-log-L4108)

**Comment by TheIllusiveC4** [comment]
```
Found mod file comforts-forge-1.18.2-5.0.0.3.jar
```

You're using the 1.18.2 version of Comforts on 1.18.1, which will cause this crash. Please downgrade to the 1.18.1 version of Comforts.

**Comment by WenXin20** [comment]
Ooh, somehow the server got the 1.18.2 version while client-side I have the 1.18.1 version.
Thanks!
