### ISSUE TITLE
Minecraft 1.19.x support

### ISSUE THREAD

**Issue by kingstairs** [TheIllusiveC4/Comforts#88]
Any plans/ETA for MC 1.19? This is a great sleeping mod and I'd like to use it in 1.19.
Thank you

**Comment by veryredpp** [comment]
bump

**Comment by doakungfu** [comment]
I'd like to contribute in any way that I can. I love this mod. Beds are stupid.

**Comment by kingstairs** [comment]
While the official Comforts 1.19.0 is in development, I went and ported the code to MC/Fabric 1.19. There is an _unofficial_ release published in my fork which you are welcome to use in the meantime: [Unofficial Comfort Releases](https://github.com/kingstairs/Comforts/releases)
#90

**Comment by doakungfu** [comment]
You're awesome! Thank you.

**Comment by TheIllusiveC4** [comment]
I've just released the 1.19 port for both Fabric and Forge. I thank everyone for their interest in the mod and their patience. Most of the code has changed so it's a beta release right now, but just let me know if there's any issues.
