### ISSUE TITLE
[Bug]: encountered an error during the common_setup event phase

### ISSUE THREAD

**Issue by krjencik** [TheIllusiveC4/Comforts#92]
### Minecraft Version

1.19.0

### What happened?

Minecraft didnt load

### How do you trigger this bug?

1. download forge 41.0.98
2.download this mod
3.run Minecraft
...

### Loader

Forge

### Loader Version

forge-41.0.98

### Mod Version

comforts-forge-6.0.0-beta.3+1.19

### Relevant Log Outputs

https://gist.github.com/krjencik/a27b17dbbc397c94aaa07acf5920ea17#file-comfortswontload-log

**Comment by TheIllusiveC4** [comment]
Yeah, this is due to the breaking changes in Forge 41.0.94+. I'll update it as soon as I can. Current workaround is to downgrade to between 41.0.64 and 41.0.93.
