### ISSUE TITLE
[Bug]: server crash

### ISSUE THREAD

**Issue by valdenoc** [TheIllusiveC4/Comforts#96]
### Minecraft Version

1.19.0

### What happened?

hello! 
i just downloaded the new forge version + the last update of the mod but it crash my server every time i try to run it. 
 this is the message i get 
![imagen_2022-07-27_123020140](https://user-images.githubusercontent.com/110125660/181346099-16875960-1636-447d-98c5-601318f6a8fa.png)

maybe im doing something wrong? anyway, i tried to remove it but it won't let me log in to the server because of missing file, thanks for the  help! 

### How do you trigger this bug?

1. remove the mod
2. change version
3.
...

### Loader

Forge

### Loader Version

forge - 1.19 - 41.1.0

### Mod Version

[6.0.0-beta.5+1.19] - 2022.07.26

**Comment by TheIllusiveC4** [comment]
Please attach the full crash log, located in the crash-reports folder. The screenshot you've shown doesn't tell me enough information about what caused the crash.

**Comment by valdenoc** [comment]
> Please attach the full crash log, located in the crash-reports folder. The screenshot you've shown doesn't tell me enough information about what caused the crash.

sorry! here you have, thanks for answer

https://mclo.gs/78K7q8e

**Comment by TheIllusiveC4** [comment]
Hmm, I think this might be a Forge issue. I'll report it to them and see what comes of it. In the meantime, I believe you can workaround this by downgrading to Forge 41.0.109 or below.

**Comment by valdenoc** [comment]
thank you so much! 
and yes, i downgraded the forge server and it works perfectly again. I will wait for the new version to work, thanks for all your work!

**Comment by gousisme** [comment]
same issue with 1.19.1 server

**Comment by TheIllusiveC4** [comment]
It's a Forge issue, not much I can do about it. We just have to wait for them to fix it.

**Comment by TigerWalts** [comment]
A temporary workaround for servers is to extract the jar files from within the `META-INF\jarjar` folder in the mod file and then place them into the server's `mods` folder. Then remove the `META-INF\jarjar` folder from the mod file.

Using 7-zip:

1. Open the mod file in 7-Zip
2. Navigate to the `META-INF\jarjar` folder
3. Extract the Jar files in this folder to the `mods` folder
4. Navigate up one level to `META-INF`
5. Remove the `jarjar` folder

I don't know if JiJ skips jars that are already loaded, if it does then you can skip steps 4 and 5.

**Comment by TheIllusiveC4** [comment]
This should be fixed now as of Forge 42.0.2. If anyone is on 1.19 still, please continue to use only Forge 41.0.109 or below to avoid the issue.
